# Generated by Django 2.2.10 on 2020-12-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='good',
            field=models.ManyToManyField(related_name='review', through='feedback.RelationshipScore', to='shop.Good'),
        ),
        migrations.AddField(
            model_name='relationshipscore',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good'),
        ),
        migrations.AddField(
            model_name='relationshipscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Score'),
        ),
    ]
