# Generated by Django 2.2.10 on 2020-10-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
