# Generated by Django 2.2.10 on 2020-10-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201024_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='attached_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_products', to='shop.Article'),
        ),
    ]
