# Generated by Django 2.2.10 on 2020-10-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201017_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='Изображение'),
        ),
    ]
