# Generated by Django 2.2.10 on 2020-10-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201024_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='attached_products',
        ),
        migrations.CreateModel(
            name='Relationship_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Article')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='article',
            field=models.ManyToManyField(related_name='attached_products', through='shop.Relationship_Article', to='shop.Article'),
        ),
    ]
