# Generated by Django 2.2.10 on 2020-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_score_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья главной страницы', 'verbose_name_plural': 'Статья главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='star',
        ),
        migrations.RemoveField(
            model_name='good',
            name='article',
        ),
        migrations.RemoveField(
            model_name='good',
            name='review',
        ),
        migrations.RemoveField(
            model_name='good',
            name='users',
        ),
        migrations.AddField(
            model_name='article',
            name='attached_products',
            field=models.ManyToManyField(related_name='article', through='shop.Relationship_Article', to='shop.Good'),
        ),
        migrations.AddField(
            model_name='relationship_user',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='good',
            field=models.ManyToManyField(related_name='review', through='shop.Relationship_Score', to='shop.Good'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='users', through='shop.Relationship_User', to='shop.Good'),
        ),
    ]
