# Generated by Django 2.2.10 on 2020-11-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201108_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship_user',
            old_name='count',
            new_name='quantity',
        ),
    ]
