# Generated by Django 2.2.10 on 2020-10-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201017_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
