# Generated by Django 2.2.10 on 2020-10-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_good_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(verbose_name=models.CharField(max_length=50)),
        ),
    ]
