# Generated by Django 2.2.10 on 2020-11-10 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201109_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_make',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
