# Generated by Django 2.2.10 on 2020-11-15 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_article_date_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name_user', models.CharField(max_length=64)),
                ('id_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='list_goods',
            field=models.ManyToManyField(related_name='order', through='shop.Relationship_Order', to='shop.Good'),
        ),
    ]
