# Generated by Django 2.2.10 on 2020-10-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_good_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
