# Generated by Django 2.2.10 on 2020-11-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201115_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='relationship_order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
