# Generated by Django 2.2.10 on 2020-10-21 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_good_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.AlterField(
            model_name='good',
            name='users',
            field=models.ManyToManyField(related_name='cart', through='shop.Relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
