# Generated by Django 2.2.10 on 2020-10-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201021_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='date_add_cart',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='good',
            name='type_good',
            field=models.CharField(max_length=50, verbose_name='Тип товара'),
        ),
    ]
