# Generated by Django 2.2.10 on 2020-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_amount_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_goods',
            field=models.IntegerField(verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_user',
            field=models.CharField(max_length=64, verbose_name='Имя заказчика'),
        ),
    ]
