# Generated by Django 2.2.10 on 2020-10-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201021_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='view_main',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
    ]
