# Generated by Django 2.2.10 on 2020-10-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_good_view_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good', verbose_name='Корзина'),
        ),
    ]
