# Generated by Django 2.2.10 on 2020-11-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201116_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=50, verbose_name='Тип товара')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='type_good',
        ),
        migrations.CreateModel(
            name='Relationship_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
                ('type_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Type_Good')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='type_good',
            field=models.ManyToManyField(related_name='goods', through='shop.Relationship_Type', to='shop.Type_Good'),
        ),
    ]
