# Generated by Django 2.2.10 on 2020-10-24 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201023_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('massage', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('attached_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.Good')),
            ],
        ),
    ]
