# Generated by Django 2.2.10 on 2020-11-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201116_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type_good',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
