# Generated by Django 2.2.10 on 2020-11-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201116_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_goods',
            field=models.IntegerField(default=0, verbose_name='Количество товара'),
        ),
    ]
