# Generated by Django 2.2.10 on 2020-10-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='attached_products',
        ),
        migrations.RemoveField(
            model_name='score',
            name='good',
        ),
        migrations.AddField(
            model_name='good',
            name='attached_products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attach_goods', to='shop.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='shop.Score'),
            preserve_default=False,
        ),
    ]
