# Generated by Django 2.2.10 on 2020-10-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201024_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='Relationship_User',
        ),
        migrations.CreateModel(
            name='Relationship_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Score')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Article')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
            ],
        ),
    ]
