# Generated by Django 2.2.10 on 2020-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201024_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='review',
        ),
        migrations.AddField(
            model_name='good',
            name='review',
            field=models.ManyToManyField(related_name='good', through='shop.Relationship_Score', to='shop.Score'),
        ),
        migrations.DeleteModel(
            name='Relationship_Article',
        ),
    ]
