# Generated by Django 2.2.10 on 2020-10-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20201024_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='attached_products',
        ),
        migrations.AddField(
            model_name='article',
            name='attached_products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='shop.Good'),
            preserve_default=False,
        ),
    ]
