# Generated by Django 2.2.10 on 2020-12-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiporder',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good'),
        ),
        migrations.AddField(
            model_name='relationshiporder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='list_goods',
            field=models.ManyToManyField(related_name='order', through='order.RelationshipOrder', to='shop.Good'),
        ),
    ]
